matrix:
  include:
    - language: python
      os:
        - linux
        # Travis does not support python on osx yet.
        # see: https://github.com/travis-ci/travis-ci/issues/2312
        # - osx
      python:
        - "2.7"
        - "3.3"
      script:
        - ./install.py
        - ./install_test.py

    - language: bash
      os:
        - linux
      addons:
        apt:
          packages:
            - ksh
            - zsh
      script:
        - ./install_test.sh

    - language: bash
      os:
        - osx
      addons:
        homebrew:
          packages:
            - ksh
            - zsh
            - shellcheck
      script:
        - ./install_test.sh
