matrix:
  include:
    - language: python
      os:
        - linux
        # Travis does not support python on osx yet.
        # see: https://github.com/travis-ci/travis-ci/issues/2312
        # - osx
      python:
        - "2.7"
        - "3.3"
      script:
        - ./install.py
        - ./install_test.py

    - language: bash
      os:
        - linux
      addons:
        apt:
          packages:
            - ksh
            - zsh
      env:
        - PATH=$HOME/bin/:$PATH
        - SHFMT_VERSION=v2.6.2
      before_script:
        - curl -sSL -o "$HOME/bin/shfmt" "https://github.com/mvdan/sh/releases/download/${SHFMT_VERSION}/shfmt_${SHFMT_VERSION}_linux_amd64"
        - chmod +x "$HOME/bin/shfmt"
      script:
        - ./install_test.sh

    - language: bash
      os:
        - osx
      addons:
        homebrew:
          packages:
            - ksh
            - zsh
            - shellcheck
            - shfmt
      script:
        - ./install_test.sh
