matrix:
  include:

    - language: bash
      os:
        - linux
      addons:
        apt:
          packages:
            - shellcheck
      env:
        - SHFMT_VERSION=2.6.2
        - PATH=$HOME/bin/:$PATH
      before_script:
        - curl -sSL -o $HOME/bin/shfmt https://github.com/mvdan/sh/releases/download/v${SHFMT_VERSION}/shfmt_v${SHFMT_VERSION}_linux_amd64
        - chmod +x $HOME/bin/shfmt
      script:
        - ./install_test.sh

    - language: bash
      os:
        - osx
      addons:
        homebrew:
          packages:
            - shellcheck
            - shfmt
      script:
        - ./install_test.sh

    - language: minimal
      os:
        - linux
      env:
        - PWSH_VERSION=6.1.2
        - PATH=$HOME/bin/pwsh:$PATH
      before_script:
        - mkdir -p $HOME/bin/pwsh
        - curl -sSL -o $HOME/bin/pwsh/pwsh.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v$PWSH_VERSION/powershell-$PWSH_VERSION-linux-x64.tar.gz
        - tar -xf $HOME/bin/pwsh/pwsh.tar.gz -C $HOME/bin/pwsh
        - chmod +x $HOME/bin/pwsh/pwsh
      script:
        - pwsh install_test.ps1

    - language: minimal
      os:
        - osx
      env:
        - PWSH_VERSION=6.1.2
        - PATH=$HOME/bin/pwsh:$PATH
      before_script:
        - mkdir -p $HOME/bin/pwsh
        - curl -sSL -o $HOME/bin/pwsh/pwsh.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v$PWSH_VERSION/powershell-$PWSH_VERSION-osx-x64.tar.gz
        - tar -xf $HOME/bin/pwsh/pwsh.tar.gz -C $HOME/bin/pwsh
        - chmod +x $HOME/bin/pwsh/pwsh
      script:
        - pwsh install_test.ps1
